# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Button"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  href:
  label:
  size:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  href: "#"
  label: Primary
  size: large

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  href:
    type: url
  size:
    type: choice
    options:
      values:
        - small
        - large
