# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Left-right-block"
  description: left right block with image
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  desktop_image: 
    image_path: ""
    image_alt: ""
  mobile_image:
    image_path: "" 
    image_alt: ""
  heading: ""
  list:
    first_item: 
    second_item: 
    third_item:
  text_block: ""
  button: bookshop:button
  


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  desktop_image: 
    image_path: /uploads/image-container.svg
    image_alt: ""
  mobile_image:
    image_path: /uploads/image-container.svg
    image_alt: ""
  heading: Find out more about what's driving the Forest Positive movement
  text_block:  >-
      Some copy here about trees, climate change, deforestation, benefits of planting and/or similar. It shouldn’t be too long, as we expect this section to not be more than this amount of lines. But there’s room for a bit more. Maybe another line.
  list: 
    first_item: First link here. A title with a hyperlink behind.
    second_item: Link here. A title with a hyperlink behind.
    third_item: Link here. A title with a hyperlink behind.
  button: bookshop:button

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  text_block:
    type: textarea
