# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Left-right-block"
  description: left right block with image
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  desktop_image: 
    image_path: 
    image_alt: 
  mobile_image:
    image_path: 
    image_alt: 
  heading: 
  text_block: 
  button: bookshop:button
  


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  desktop_image: 
    image_path: /uploads/image-container.svg
    image_alt: cartoon style image of woman sitting on green park bench with a black and grey dog
  mobile_image: ""
    image_path: /uploads/image-container.svg
    image_alt: cartoon style image of woman sitting on green park bench with a black and grey dog
  heading: Find out more about what's driving the Forest Positive movement
  text_block:  >-
      Some copy here about trees, climate change, deforestation, benefits of planting and/or similar. It shouldn’t be too long, as we expect this section to not be more than this amount of lines. But there’s room for a bit more. Maybe another line.
  button: bookshop:button

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
